### ISSUE TITLE
How is it used with gpuimage?

### ISSUE THREAD

**Issue by idevplay** [natario1/ZoomLayout#149]
I want use this lib and gpuimage:
        `gpuimage.setGLSurfaceView(binding.zoomLayout)`
but error:
 ```
Caused by: java.lang.IllegalStateException: setRenderer has already been called for this instance.
        at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1896)
        at android.opengl.GLSurfaceView.setEGLContextClientVersion(GLSurfaceView.java:474)
        at jp.co.cyberagent.android.gpuimage.GPUImage.setGLSurfaceView(GPUImage.java:109)
```
How to fix it and make zoomlayout as display view?Thank you.

**Comment by natario1** [comment]
I don't think you can use setGLSurfaceView(). Does GPUImage have a setSurface method instead? If so, you could pass ZoomSurfaceView's surface into it

**Comment by idevplay** [comment]
@natario1 Thank you for your answer. I didn't find a way to pass the surface in gpuimage. Since I lacked knowledge of the surface and opengl glsurfaceview, I needed a few days to learn. There is also a question about cameraview, can the real-time filter support the lookupFilter similar to gpuimage for the 512*512 LUT PNG real-time filter?

**Comment by natario1** [comment]
If you write one, sure! You can adapt the shaders from gpuimage with some work

**Comment by idevplay** [comment]
Thank you for your advice.

**Comment by Dimezis** [comment]
@idevplay In case you're still interested in making ZoomSurfaceView work with GpuImage, what I did is forked the ZoomSurfaceView, removed GLSurfaceView.Renderer part from it, and moved its matrix math from onDrawFrame to onUpdate, where I update the matrix of `GPUImageTransformFilter` shader and request render. The `GPUImageTransformFilter` has to be first in your `GPUImageFilterGroup` pipeline.
Works great and the changes are pretty simple to make.

@natario1 Thanks for the library, you saved me a lot of time.
I wonder what you think about making `ZoomSurfaceView` independent from its Renderer, because right now it's limiting the integration with the code that relies on own Renderers.
Obviously it's a lot to ask, so I'm rather just curious about your opinion

**Comment by natario1** [comment]
I think the issue is with GPUImage design, which is only capable of sending output to `GLSurfaceView` directly, and has weird input APIs as well. I/O of graphic buffers in Android should use the `Surface` object, anything else will not be versatile enough.

ZSF is designed to be a black box - you write into its input `Surface` and it re-renders a zoomed version of the texture into its output `Surface`, which means on screen. This encourages a clean pipeline of rendering steps and keeps zoom code safe in my opinion. If GPUImage was `Surface`-based, you would simply call `gpuImage.outputSurface = zsf.inputSurface` and that's it.

There are many ways to write into a surface,

1. Pass it to external producers (camera1, camera2, MediaCodec)
2. For canvas rendering, use `Surface.lockCanvas()`
3. If you render with GL commands, you need just a few lines of code to replicate what GLSurfaceView.Renderer does. Create a thread, create a GL context (`core = EglCore()`) and create a GL window (`window = EglWindowSurface(core, zoomSurfaceView.inputSurface)`). Then on every frame, make the window current (`window.makeCurrent()`), add your rendering code, and finally publish (`window.swapBuffers()`). If you are rendering with GL you probably know what this stuff is.

So with 3. you can replicate a GLSurfaceView.Renderer behavior easily I think. Then, if you **really** want control over the view, and you don't want to write into ZSF input, but you rather want to apply zooming and rendering in the same I/O step... you can do exactly what you have right now:

4. Drop ZSF and use `ZoomEngine` directly in your own GL view. Just pass touch events to the engine and handle its matrix updates (e.g. pass matrix to `GPUImageTransformFilter`). It's a legit solution, much less elegant than option 3 but apparently it's the only way to use GPUImage with their current APIs.
