### ISSUE TITLE
How to Restrict the pan area and zoom inside the view

### ISSUE THREAD

**Issue by shivammaindola** [natario1/ZoomLayout#161]
I have an image inside zoomlayout and I want it to zoom to some limit like to only inside the main view. how to do this?

**Comment by markusressel** [comment]
Well, if you use `app:transformation="centerCrop"` then `zoom=1.0` will match your parent views dimensions, at least on the shorter end. If you use `app:transformation="centerInside"` it will fit completely. Otherwise you probably have to do some math to find the correct zoom value depending on the image and parent views dimensions.

Btw, if you only have an image inside a `ZoomLayout` you could think about using `ZoomImageView` instead.

**Comment by shivammaindola** [comment]
@markusressel Okay cool. How can I limit its horizontal pan to parent width?

**Comment by markusressel** [comment]
You can have a look at how the `ZoomEngine` does it for `centerCrop` and `centerInside` [here](https://github.com/natario1/ZoomLayout/blob/f47d9a6ccec1ca521bdea7945d16aefa17247934/library/src/main/java/com/otaliastudios/zoom/ZoomEngine.kt#L586). If you want to only use the horizontal axis it simplifies it even more. Then you can set the `maxZoom` to your desired value.

**Comment by shivammaindola** [comment]
@markusressel I need to do this. Please explain to me how can I achieve this in steps.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39567362/85504154-03a00100-b609-11ea-9642-ee851dec799e.gif)

**Comment by markusressel** [comment]
To me, it looks like the `centerInside` transformation is sufficient for your use case, with a `maxZoom` set to `1.0`.

**Comment by shivammaindola** [comment]
@markusressel still it is going outside borders. How can I restrict the image to not to go out of boundary?

**Comment by shivammaindola** [comment]
@markusressel Is there any method to set a limit of the horizontal pan?

**Comment by markusressel** [comment]
Did you try `app:overScrollHorizontal="false"`? Otherwise no, there is currently no built in way to do that.
