### ISSUE TITLE
How to Pan with overscroll?

### ISSUE THREAD

**Issue by CyberNyanta** [natario1/ZoomLayout#48]
I need to center some object that located near Layout corner, I could to it with touch, however, I have to do it programmatically, any Ideas? 
P.S.  I'm making some kind of floor map, scroll like in AirBnb map
<img width="285" alt="screen shot 2018-08-28 at 5 52 11 pm" src="https://user-images.githubusercontent.com/10977301/44731161-449d5c00-aaeb-11e8-919a-83ecac7b42d3.png">

**Comment by natario1** [comment]
If the object is near the corner, to center it, you would have to zoom. Overscroll can only be temporary. You have to do some calculations here and use moveTo, it's not impossible, but not easy either. Maybe one day we will provide an helper method

**Comment by CyberNyanta** [comment]
>  Overscroll can only be temporary. 

I've already made it persistent with touch event
However, I having troubles to make it programmatically,

**Comment by CyberNyanta** [comment]
Maybe I should call fling event from code

**Comment by markusressel** [comment]
@CyberNyanta Any takeway to document/PR on this?

**Comment by CyberNyanta** [comment]
@markusressel I achieved what I wanted, however, I did this on C# via Xamarin
If you facing the same problem I could help

**Comment by markusressel** [comment]
If we could extract your code into some kind of helper method that allows to center appoint by automatically calculating the appropriate zoom to pan without overscroll that would be pretty neat.

If your solution involves keeping overscroll permanent I don't think it would fit into this library as a method because it changes the intended default behavior of the library and that I would leave the developer using this library to figure out. However you can always provide some sample code to help others with the same problem as you (even if it's C#).

**Comment by markusressel** [comment]
@CyberNyanta are you interested? Otherwise I would close this issue as it seems to be resolved.

**Comment by markusressel** [comment]
I'm closing this for now. Feel free to reopen or open a PR if you feel the urge to contribute back to the community :rocket:
